AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  postMessage:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: postMessage
      Handler: src/index.postMessage
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  getConversation:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: getConversation
      Handler: src/index.getConversation
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  sendPushNotifications:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: sendPushNotifications
      Handler: src/index.sendPushNotifications
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  updateUserInAllMessages:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: updateUserInAllMessages
      Handler: src/index.updateUserInAllMessages
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  updateUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: updateUser
      Handler: src/index.updateUser
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  getConversationHistory:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: getConversationHistory
      Handler: src/index.getConversationHistory
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  initiateConversation:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: initiateConversation
      Handler: src/index.initiateConversation
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  registerUserWithPhoneNumber:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: registerUserWithPhoneNumber
      Handler: src/index.registerUserWithPhoneNumber
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  registerUserWithEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: registerUserWithEmail
      Handler: src/index.registerUserWithEmail
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile


  lookupUserByPhoneNumber:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lookupUserByPhoneNumber
      Handler: src/index.lookupUserByPhoneNumber
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

  lookupUserByEmail:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lookupUserByEmail
      Handler: src/index.lookupUserByEmail
      Runtime: nodejs8.10
      Role: !Ref LambdaRole
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref ZipFile

Parameters:
  ZipFile:
    Type: String
  BucketName:
    Type: String
  LambdaRole:
    Type: String
